### ISSUE TITLE
server: should export liveness metrics

### ISSUE THREAD

**Issue by bassosimone** [neubot/dash#4]
As discussed with @robertodauria it is possible to specify a path that should respond to an HTTP GET therefore the smartest way is to just export an URL for this purpose. We can probably use prometheus for this purpose, and specifically the `/metrics` endpoint.

**Comment by robertodauria** [comment]
I think this can be closed. We are using a `httpGet` liveness probe based on the HTTP status code returned by `/metrics` (200 = alive, not 200 = not alive.)

**Comment by bassosimone** [comment]
Thanks!
